---
name: CI-Config-Functions

on:
  push:
    branches:
      - "main"
    paths:
      - "kiwi/config/functions.sh"
      - ".github/workflows/**"
      - "test/scripts/**"
      - "pyproject.toml"
  pull_request:
    paths:
      # copy-pasta from the above because workflows don't support anchors :-(
      - "kiwi/config/functions.sh"
      - ".github/workflows/**"
      - "test/scripts/**"
      - "pyproject.toml"

jobs:
  scripts_integration_tests:
    name: Integration tests for config/functions.sh
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container_runtime:
          - PODMAN
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
          key: pip-${{ hashFiles('.virtualenv.dev-requirements.txt') }}-${{ hashFiles('.virtualenv.requirements.txt') }}
          restore-keys: |
            -pip-

      - name: checkout source code
        uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v4
      - name: Install Poetry
        run: |
          sudo python -m pip install --upgrade pip
          sudo python -m pip install poetry

      - name: Run the scripts integration tests
        run: sudo make test_scripts
        env:
          CONTAINER_RUNTIME: ${{ matrix.container_runtime }}
